# spring
spring:
  application:
    name: nerDatasetScraper

  #profile 설정을 안했을 시 active profile
  profiles:
    active: local

---

spring:
  profiles: local
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://127.0.0.1:3306/cve_cpe?useUnicode=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&useServerPrepStmts=true&rewriteBatchedStatements=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true"
    username: "cve_cpe"
    password: "cve_cpe!@#"

mybatis:
  mapper-locations: "classpath:mybatis/mapper/**/*.xml"